CREATE GLOBAL TEMPORARY TABLE TODOS_EMPLEADOS AS
SELECT E.*, R.FECHA_FIN_CONTRATO, R.NUM_CONTRATO, ED.NUM_CEDULA, ED.TITULO
FROM EMPLEADO E
LEFT JOIN REVISOR R
ON E.EMPLEADO_ID = R.EMPLEADO_ID
LEFT JOIN EDITOR ED
ON E.EMPLEADO_ID = ED.EMPLEADO_ID;