-- @Autores: López Santibáñez Jiménez, Luis Gerardo
--          Silva García, Carlos Sebastián
-- Fecha de creación: 09/06/2018
-- Descripción: Crea índices en campos de interés


CREATE UNIQUE INDEX AREA_INTERES_IX ON AREA_INTERES(AREA_INTERES_ID);
CREATE UNIQUE INDEX ARTICULO_IX ON ARTICULO(ARTICULO_ID);
CREATE UNIQUE INDEX ARTICULO_PDF_IX ON ARTICULO_PDF(ARTICULO_PDF_ID);
CREATE UNIQUE INDEX AUTOR_IX ON AUTOR(AUTOR_ID);
CREATE UNIQUE INDEX EMPLEADO_IX ON EMPLEADO(EMPLEADO_ID);
CREATE UNIQUE INDEX REVISTA_IX ON REVISTA(REVISTA_ID);
CREATE UNIQUE INDEX SUSCRIPTOR_IX ON SUSCRIPTOR(SUSCRIPTOR_ID);


CREATE INDEX ARTICULO_FOLIO_IX ON ARTICULO(FOLIO);
CREATE INDEX EDITOR_NUM_CED_IX ON EDITOR(NUM_CEDULA);
CREATE INDEX EMPLEAD_NOMBRE_IX ON EMPLEADO(NOMBRE);
CREATE INDEX REVISOR_NUM_CONTRAT_IX ON REVISOR(NUM_CONTRATO);
CREATE INDEX REVISTA_TITULO_IX ON REVISTA(TITULO);
CREATE INDEX SUSCRIPTOR_EMAIL ON SUSCRIPTOR(EMAIL);



