-- @Autores: López Santibáñez Jiménez, Luis Gerardo
--          Silva García, Carlos Sebastián
-- Fecha de creación: 09/06/2018
-- Descripción: Crea índices en campos de interés


CREATE INDEX ARTICULO_FOLIO_IX ON ARTICULO(FOLIO);
CREATE INDEX EDITOR_NUM_CED_IX ON EDITOR(NUM_CEDULA);
CREATE INDEX EMPLEAD_NOMBRE_IX ON EMPLEADO(lower(NOMBRE));
CREATE INDEX REVISOR_NUM_CONTRAT_IX ON REVISOR(NUM_CONTRATO);
CREATE INDEX REVISTA_TITULO_IX ON REVISTA(lower(TITULO));
CREATE INDEX SUSCRIPTOR_EMAIL ON SUSCRIPTOR(EMAIL);


-- Índices únicos para verificar aquellos que tienen iguales apellidos
CREATE UNIQUE INDEX SUSCRIPTOR_AP_UIX ON SUSCRIPTOR(AP_PATERNO, AP_MATERNO);
CREATE UNIQUE INDEX EMPLEADO_AP_UIX ON EMPLEADO(AP_PATERNO, AP_MATERNO);

-- Índices para llaves foráneas consultadas constantemente
CREATE INDEX ARTICULO_AUTOR_ART_IX ON ARTICULO_AUTOR(ARTICULO_ID); 
CREATE INDEX ARTICULO_AUTOR_AUT_IX ON ARTICULO_AUTOR(AUTOR_ID); 

CREATE INDEX ARTICULO_REVISTA_ART ON ARTICULO_REVISTA(ARTICULO_ID); 
CREATE INDEX ARTICULO_REVISTA_REV ON ARTICULO_REVISTA(REVISTA_ID); 

CREATE INDEX SUS_REVISTA_SUS_IX ON SUSCRIPTOR_REVISTA(SUSCRIPTOR_ID); 
CREATE INDEX SUS_REVISTA_REV_IX ON SUSCRIPTOR_REVISTA(REVISTA_ID); 




