-- @Autores: López Santibáñez Jiménez, Luis Gerardo
--          Silva García, Carlos Sebastián
-- Fecha de creación: 09/06/2018
-- Descripción: Crea sinónimos para los demás usuarios


--TODO: Cambiar de usuario a admin desde sqlplus
CONNECT LSSG_PROY_ADMIN/LSSG_PROY_ADMIN;
CREATE PUBLIC SYNONYM SYN_STATUS_ARTICULO
 FOR LSSG_PROY_ADMIN.EMPLEADO;
 
CREATE PUBLIC SYNONYM SYN_ARTICULO
 FOR LSSG_PROY_ADMIN.ARTICULO;
 
 CREATE PUBLIC SYNONYM SYN_REVISTA
 FOR LSSG_PROY_ADMIN.REVISTA;
 
 CREATE PUBLIC SYNONYM SYN_AREA_INTERES
 FOR LSSG_PROY_ADMIN.AREA_INTERES;
 
 CREATE PUBLIC SYNONYM SYN_ARTICULO_PDF
 FOR LSSG_PROY_ADMIN.ARTICULO_PDF;
 

GRANT SELECT ON EMPLEADO TO LSSG_PROY_INVITADO;
GRANT SELECT ON ARTICULO TO LSSG_PROY_INVITADO;
GRANT SELECT ON REVISTA TO LSSG_PROY_INVITADO;
GRANT SELECT ON AREA_INTERES TO LSSG_PROY_INVITADO;
GRANT SELECT ON ARTICULO_PDF TO LSSG_PROY_INVITADO;


 --TODO: Cambiar de usuario a solo_leer desde sqlplus
 CONNECT LSSG_PROY_INVITADO/LSSG_PROY_INVITADO;
CREATE SYNONYM EMPLEADO
FOR LSSG_PROY_ADMIN.EMPLEADO;

CREATE SYNONYM ARTICULO
FOR LSSG_PROY_ADMIN.ARTICULO;

CREATE SYNONYM REVISTA
FOR LSSG_PROY_ADMIN.REVISTA;

CREATE SYNONYM AREA_INTERES
FOR LSSG_PROY_ADMIN.AREA_INTERES;

CREATE SYNONYM ARTICULO_PDF
FOR LSSG_PROY_ADMIN.ARTICULO_PDF;


-- add synonyms with xx as prefix

BEGIN 
FOR i IN (SELECT t.table_name AS old_name
              FROM user_tables t )
LOOP
  EXECUTE IMMEDIATE 'create synonym xx_' || i.old_name || ' for ' || i.old_name;
END LOOP;
END; 
/

