-- @Autores: López Santibáñez Jiménez, Luis Gerardo
--          Silva García, Carlos Sebastián
-- Fecha de creación: 09/06/2018
-- Descripción: Crea vistas para simplificar queries. 

CREATE VIEW REVISTA_PUBLIC AS
SELECT TITULO, ANIO_PUBLICACION, BIMESTRE
FROM REVISTA;

CREATE VIEW NOMBRES_EMPLEADOS AS
SELECT NOMBRE, AP_PATERNO, AP_MATERNO
FROM EMPLEADO;

CREATE VIEW ARTICULOS_EN_REVISTA AS 
SELECT A.TITULO, A.SINOPSIS, R.ANIO_PUBLICACION
FROM ARTICULO A, REVISTA R, ARTICULO_REVISTA AR
WHERE AR.REVISTA_ID = R.REVISTA_ID
AND AR.ARTICULO_ID = A.ARTICULO_ID;