-- @Autores: López Santibáñez Jiménez, Luis Gerardo
--          Silva García, Carlos Sebastián
-- Fecha de creación: 10/06/2018
-- Descripción: Calcula el promedio de un artículo

CREATE OR REPLACE PROCEDURE CALCULA_PROMEDIO(
    V_ARTICULO_ID IN ARTICULO.ARTICULO_ID%TYPE
)
IS
  V_PROMEDIO NUMBER(5, 2);
BEGIN
  IF V_ARTICULO_ID IS NOT NULL THEN
    SELECT AVG(CALIFICACION)
    INTO V_PROMEDIO 
    FROM  ARTICULO_REVISOR
    WHERE ARTICULO_ID = V_ARTICULO_ID;
    
    UPDATE ARTICULO
    SET PROMEDIO = V_PROMEDIO
    WHERE ARTICULO_ID = V_ARTICULO_ID;
    DBMS_OUTPUT.PUT_LINE('SE HA ENVIADO EL CORREO A LA AFAMILIA.MUCHAS GRACIAS.');
     
    
  ELSIF V_ARTICULO_ID IS NULL THEN 
  DBMS_OUTPUT.PUT_LINE('DEBES ENVIAR EL ID DEL ARTICULO');
  COMMIT;
  
  END IF;

END;
/
